apiVersion: aadpodidentity.k8s.io/v1
kind: AzureIdentity
metadata:
  name: demo-aad1
spec:
  type: 0
  ResourceID: /subscriptions/<SUBSCRIPTION_ID>/resourcegroups/<RESOURCE_GROUP>/providers/Microsoft.ManagedIdentity/userAssignedIdentities/demo-aad1
  ClientID: <CLIENT_ID>
